// Code generated by MockGen. DO NOT EDIT.
// Source: git.go

// Package gist is a generated GoMock package.
package gist

import (
	gomock "github.com/golang/mock/gomock"
	go_git_v4 "gopkg.in/src-d/go-git.v4"
	object "gopkg.in/src-d/go-git.v4/plumbing/object"
	reflect "reflect"
)

// Mockrepoer is a mock of repoer interface
type Mockrepoer struct {
	ctrl     *gomock.Controller
	recorder *MockrepoerMockRecorder
}

// MockrepoerMockRecorder is the mock recorder for Mockrepoer
type MockrepoerMockRecorder struct {
	mock *Mockrepoer
}

// NewMockrepoer creates a new mock instance
func NewMockrepoer(ctrl *gomock.Controller) *Mockrepoer {
	mock := &Mockrepoer{ctrl: ctrl}
	mock.recorder = &MockrepoerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *Mockrepoer) EXPECT() *MockrepoerMockRecorder {
	return m.recorder
}

// Worktree mocks base method
func (m *Mockrepoer) Worktree() (*go_git_v4.Worktree, error) {
	ret := m.ctrl.Call(m, "Worktree")
	ret0, _ := ret[0].(*go_git_v4.Worktree)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Worktree indicates an expected call of Worktree
func (mr *MockrepoerMockRecorder) Worktree() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Worktree", reflect.TypeOf((*Mockrepoer)(nil).Worktree))
}

// Log mocks base method
func (m *Mockrepoer) Log(arg0 *go_git_v4.LogOptions) (object.CommitIter, error) {
	ret := m.ctrl.Call(m, "Log", arg0)
	ret0, _ := ret[0].(object.CommitIter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Log indicates an expected call of Log
func (mr *MockrepoerMockRecorder) Log(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Log", reflect.TypeOf((*Mockrepoer)(nil).Log), arg0)
}

// Push mocks base method
func (m *Mockrepoer) Push(arg0 *go_git_v4.PushOptions) error {
	ret := m.ctrl.Call(m, "Push", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Push indicates an expected call of Push
func (mr *MockrepoerMockRecorder) Push(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Push", reflect.TypeOf((*Mockrepoer)(nil).Push), arg0)
}
